[phases.setup]
nixPkgs = ["nodejs-18_x", "python3", "ffmpeg"]

[phases.install]
cmds = [
  "pip3 install --user yt-dlp",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
PATH = "/root/.local/bin:$PATH"

