[phases.setup]
nixPkgs = ["nodejs-18_x", "ffmpeg", "wget"]

[phases.install]
cmds = [
  "wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O yt-dlp",
  "chmod a+rx yt-dlp",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

